import { AIGuidanceCard } from "@/components/AIGuidanceCard";
import { ReportComposer } from "@/components/ReportComposer";
import { ReportExportHistory } from "@/components/ReportExportHistory";
import { ExecutiveCircleReport } from "@/components/ExecutiveCircleReport";
import { ManagementReport } from "@/components/ManagementReport";
import { trpc } from "@/lib/trpc";
import { BarChart3, Building2, ClipboardList, GraduationCap, Users } from "lucide-react";

export default function Reports() {
  const { data: stats } = trpc.dashboard.stats.useQuery();
  const { data: centers } = trpc.centers.list.useQuery({ orgId: undefined });
  const { data: teachers } = trpc.teachers.list.useQuery({ centerId: undefined });
  const { data: students } = trpc.students.list.useQuery({});
  const { data: sessions } = trpc.sessions.list.useQuery({ circleId: undefined, seasonId: undefined });
  const { data: circles } = trpc.circles.list.useQuery({ branchId: undefined, seasonId: undefined });
  const sessionsByStatus = { scheduled: sessions?.filter((session) => session.status === "scheduled").length ?? 0, open: sessions?.filter((session) => session.status === "open").length ?? 0, closed: sessions?.filter((session) => session.status === "closed").length ?? 0, cancelled: sessions?.filter((session) => session.status === "cancelled").length ?? 0 };
  return <div className="space-y-7" dir="rtl"><header className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><BarChart3 className="h-5 w-5" /></span><div><h1 className="page-title">التقارير والإحصائيات</h1><p className="page-subtitle">أنشئ تقريراً منظمًا، عاينه ثم اطبعه أو شاركه أو صدّره.</p></div></div></header><AIGuidanceCard context="reports" /><ManagementReport centers={centers ?? []} /><ExecutiveCircleReport circles={circles ?? []} /><ReportComposer circles={circles ?? []} students={students ?? []} /><section className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ label: "إجمالي الطلاب", value: stats?.totalStudents ?? 0, icon: Users }, { label: "المعلمون", value: stats?.totalTeachers ?? 0, icon: GraduationCap }, { label: "المراكز", value: stats?.totalCenters ?? 0, icon: Building2 }, { label: "إجمالي الفترات", value: stats?.totalSessions ?? 0, icon: ClipboardList }].map((card) => { const Icon = card.icon; return <div key={card.label} className="glass-card rounded-2xl p-4"><div className="flex items-start justify-between"><div><p className="text-sm text-muted-foreground">{card.label}</p><p className="mt-1 font-display text-3xl font-bold text-foreground">{card.value}</p></div><Icon className="h-5 w-5 text-primary" /></div></div>; })}</section><section className="grid gap-5 lg:grid-cols-2"><div className="glass-card rounded-2xl p-5"><h2 className="font-display text-lg font-bold text-foreground">حالة الفترات</h2><div className="mt-4 space-y-3">{[{ label: "مجدولة", value: sessionsByStatus.scheduled }, { label: "مفتوحة", value: sessionsByStatus.open }, { label: "مغلقة", value: sessionsByStatus.closed }, { label: "ملغاة", value: sessionsByStatus.cancelled }].map((item) => <div key={item.label} className="flex items-center justify-between rounded-xl bg-muted/30 px-3 py-2 text-sm"><span className="text-muted-foreground">{item.label}</span><span className="font-semibold text-foreground">{item.value}</span></div>)}</div></div><div className="glass-card rounded-2xl p-5"><h2 className="font-display text-lg font-bold text-foreground">المراكز والمعلمون</h2><p className="mt-2 text-sm text-muted-foreground">{centers?.filter((center) => center.isActive).length ?? 0} مراكز نشطة · {teachers?.filter((teacher) => teacher.isActive).length ?? 0} معلمين نشطين</p><ReportExportHistory /></div></section></div>;
}
