import { Building2, KeyRound, ShieldCheck, UserRoundCheck } from "lucide-react";

export function AccessHelpPanel({ onCreateCenter, onRedeemCode }: { onCreateCenter?: () => void; onRedeemCode?: () => void }) {
  return <section className="mt-5 rounded-2xl border border-primary/15 bg-primary/5 p-4 text-right" aria-label="مركز دعم الوصول">
    <div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary" aria-hidden="true" /><h2 className="font-display text-base font-bold text-foreground">دليل الوصول الآمن</h2></div>
    <div className="mt-3 grid gap-3 text-sm leading-6 text-muted-foreground"><div className="flex gap-2.5"><Building2 className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" /><p><strong className="text-foreground">مدير مركز جديد:</strong> سجّل الدخول أولاً، ثم اختر «إنشاء مركز جديد». لا تستخدم كود مركز آخر إذا كنت تريد إدارة مستقلة.</p></div><div className="flex gap-2.5"><KeyRound className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" /><p><strong className="text-foreground">معلم أو طالب أو ولي أمر:</strong> سجّل الدخول بالحساب الصحيح، ثم استرد كود الوصول الممنوح لك من الإدارة.</p></div><div className="flex gap-2.5"><UserRoundCheck className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" /><p>لتبديل الحساب، استخدم نافذة خاصة أو ملف متصفح آخر إذا أعاد موفر الدخول فتح الحساب السابق تلقائياً. لا تشارك كودك أو كلمة مرورك.</p></div></div>
    {(onCreateCenter || onRedeemCode) && <div className="mt-4 grid gap-2 sm:grid-cols-2">{onCreateCenter && <button type="button" onClick={onCreateCenter} className="rounded-xl border border-primary/25 bg-background px-3 py-2.5 text-sm font-bold text-primary transition-colors hover:bg-primary/10">إنشاء مركز مستقل</button>}{onRedeemCode && <button type="button" onClick={onRedeemCode} className="rounded-xl border border-border bg-background px-3 py-2.5 text-sm font-bold text-foreground transition-colors hover:bg-muted">استرداد كود الدخول</button>}</div>}
  </section>;
}
