import { BookOpen, CalendarDays, ChevronLeft, FileText, Star } from "lucide-react";

export function ReportPreview({ report }: { report: any }) {
  const period = report.meta.startDate && report.meta.endDate ? `من ${new Date(report.meta.startDate).toLocaleDateString("ar-SA")} إلى ${new Date(report.meta.endDate).toLocaleDateString("ar-SA")}` : "كامل البيانات المتاحة";
  const totalAttendance = report.summary.present + report.summary.absent + report.summary.late + report.summary.excused;
  return <article className="report-print-area mx-auto max-w-4xl rounded-3xl border border-border bg-background p-5 text-right shadow-sm sm:p-8" dir="rtl">
    <header className="flex flex-col gap-5 border-b border-primary/25 pb-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><BookOpen className="h-6 w-6" /></div><div><p className="font-display text-xl font-bold text-foreground">ترتيل</p><p className="text-xs text-muted-foreground">إدارة مراكز القرآن الكريم</p></div></div><div className="sm:text-left"><h1 className="font-display text-2xl font-bold text-foreground">{report.meta.title}</h1><p className="mt-1 font-semibold text-primary">{report.meta.typeLabel}</p><p className="mt-1 inline-flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="h-3.5 w-3.5" />{period}</p></div></header>
    {report.sections.summary && <section className="mt-6"><SectionTitle title="ملخص الحلقة" /><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><Summary label="الطلاب" value={report.summary.students} /><Summary label="الحضور" value={report.summary.present} /><Summary label="الغياب" value={report.summary.absent} /><Summary label="نسبة الحضور" value={`${report.summary.attendanceRate}%`} /><Summary label="عمليات الحفظ" value={report.summary.memorizationCount} /><Summary label="عمليات المراجعة" value={report.summary.revisionCount} /><Summary label="متوسط التقييم" value={report.summary.averageScore ? `${report.summary.averageScore}/100` : "—"} /><Summary label="إجمالي السجلات" value={totalAttendance} /></div></section>}
    {report.sections.attendance && <section className="mt-7"><SectionTitle title="بيانات الحضور" /><div className="mt-3 overflow-x-auto rounded-2xl border border-border"><table className="min-w-[620px] w-full text-sm"><thead className="bg-primary text-primary-foreground"><tr><th className="p-3 text-right font-bold">الاسم</th><th className="p-3 text-center font-bold">الحضور</th><th className="p-3 text-center font-bold">الاستئذان</th><th className="p-3 text-center font-bold">الغياب</th><th className="p-3 text-center font-bold">الإجمالي</th></tr></thead><tbody>{report.students.map((block: any, index: number) => <tr key={block.student.id} className={index % 2 ? "bg-muted/25" : "bg-background"}><td className="p-3 font-semibold text-foreground">{block.student.name}</td><td className="p-3 text-center">{block.attendance.present}</td><td className="p-3 text-center">{block.attendance.excused}</td><td className="p-3 text-center">{block.attendance.absent}</td><td className="p-3 text-center font-semibold">{block.attendance.total}</td></tr>)}{!report.students.length && <EmptyTable text="لا يوجد طلاب ضمن معايير التقرير." colSpan={5} />}</tbody></table></div></section>}
    {(report.sections.memorization || report.sections.revision || report.sections.evaluations) && <section className="mt-7"><SectionTitle title="الحفظ والمراجعة" /><div className="mt-3 space-y-4">{report.students.map((block: any) => <StudentBlock key={block.student.id} block={block} sections={report.sections} />)}{!report.students.length && <p className="rounded-2xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">لا توجد بيانات طلاب لإظهارها.</p>}</div></section>}
    <footer className="mt-8 flex items-center justify-between border-t border-border pt-4 text-xs text-muted-foreground"><span>تم التوليد بواسطة تطبيق ترتيل</span><span>{new Date(report.meta.generatedAt).toLocaleString("ar-SA")}</span></footer>
  </article>;
}

function StudentBlock({ block, sections }: { block: any; sections: any }) { const rows = [...(sections.memorization ? block.memorization : []), ...(sections.revision ? block.revision : [])].sort((a: any, b: any) => new Date(b.date).getTime() - new Date(a.date).getTime()); return <section className="break-inside-avoid rounded-2xl border border-border bg-card"><div className="flex flex-wrap items-center justify-between gap-2 rounded-t-2xl bg-muted/50 px-4 py-3"><h3 className="font-display text-lg font-bold text-foreground">{block.student.name}</h3><div className="flex items-center gap-2 text-xs text-muted-foreground">{block.averageScore !== null && <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2 py-1 text-primary"><Star className="h-3.5 w-3.5" fill="currentColor" />{block.averageScore}/100</span>}<span>{block.attendance.present}/{block.attendance.total} حضور</span></div></div><div className="overflow-x-auto"><table className="min-w-[650px] w-full text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="p-3 text-right">النوع</th><th className="p-3 text-right">من</th><th className="p-3 text-right">إلى</th><th className="p-3 text-center">الصفحات</th><th className="p-3 text-center">التقدير</th><th className="p-3 text-center">التاريخ</th></tr></thead><tbody>{rows.map((row: any, index: number) => <tr key={`${row.kind}-${row.id}`} className={index % 2 ? "bg-muted/20" : ""}><td className="p-3 font-semibold text-foreground">{row.kind === "memorization" ? "حفظ" : "مراجعة"}</td><td className="p-3">{row.from}</td><td className="p-3">{row.to}</td><td className="p-3 text-center">{row.pages ?? "—"}</td><td className="p-3 text-center">{row.grade ?? "—"}</td><td className="p-3 text-center text-xs text-muted-foreground">{new Date(row.date).toLocaleDateString("ar-SA")}</td></tr>)}{!rows.length && <EmptyTable text="لا توجد عمليات حفظ أو مراجعة خلال الفترة المحددة." colSpan={6} />}</tbody></table></div>{sections.evaluations && block.evaluations.length > 0 && <div className="border-t border-border px-4 py-3 text-sm text-muted-foreground">آخر تقييم: <span className="font-semibold text-foreground">{block.evaluations[0].rating}</span> · {block.evaluations[0].score ?? "—"}/100</div>}</section>; }
function Summary({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-border bg-muted/25 p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-display text-xl font-bold text-foreground">{value}</p></div>; }
function SectionTitle({ title }: { title: string }) { return <div className="flex items-center gap-2"><span className="h-5 w-1 rounded-full bg-primary" /><h2 className="font-display text-xl font-bold text-foreground">{title}</h2><ChevronLeft className="h-4 w-4 text-primary" /></div>; }
function EmptyTable({ text, colSpan }: { text: string; colSpan: number }) { return <tr><td colSpan={colSpan} className="p-7 text-center text-muted-foreground">{text}</td></tr>; }
